apiVersion: v1
kind: Namespace
metadata:
  name: spring-cloud
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-service
  namespace: spring-cloud
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8100
    targetPort: 8100
  selector:
    app: eureka-pod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spring-cloud-controller
  namespace: spring-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-pod
  serviceName: spring-cloud-service
  template:
    metadata:
      name: eureka-pod  # 此处的name只是一个占位符，因为name字段比如有，pod最后的名字会是控制器的名字加上一个数字：spring-cloud-controller-0
      namespace: spring-cloud
      labels:
        app: eureka-pod
    spec:
      containers:
      - name: eureka-container  # 此处的name只是一个标识，比如我们在set image的时候需要-c指定修改哪个容器的镜像，那么此时就需要用到这里的name来指定要更新的容器
        image: eureka:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: eureka-port
          containerPort: 8100
          hostPort: 8100
