debug: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
spring:
  application:
    name: eureka-server
server:
  port: 8100